BEGIN;

ALTER TABLE IF EXISTS workflow_run
    ADD COLUMN IF NOT EXISTS worker_id UUID REFERENCES worker (id) ON DELETE SET NULL;
ALTER TABLE IF EXISTS task_run
    ADD COLUMN IF NOT EXISTS worker_id UUID REFERENCES worker (id) ON DELETE SET NULL;

COMMIT;
