name: go

concurrency:
  group: ${{ github.workflow }}/${{ github.ref_name }}

on:
  push:
    paths:
      - '**.go'
      - '**.sql'
      - '**.mod'
      - '**.sum'
      - '.github/workflows/go.yml'
    branches:
      - main
  pull_request:
    paths:
      - '**.go'
      - '**.sql'
      - '**.mod'
      - '**.sum'
      - '.github/workflows/go.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run tests
        run: make test

  lint:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Vet
        run: make lint

  generate:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run generators
        run: make generate

      - name: Check for changes
        run: |
          git add .
          git diff --staged --exit-code

  format:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Run formatters
        run: make format

      - name: Check for changes
        run: |
          git add .
          git diff --staged --exit-code
